image:
  file: .gitpod.Dockerfile

ports:
  - name: Web App
    port: 8080
    onOpen: open-preview

vscode:
  extensions:
    # see: https://open-vsx.org/
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - Pivotal.vscode-boot-dev-pack
    - pivotal.vscode-spring-boot
    - vscjava.vscode-spring-boot-dashboard
    - vscjava.vscode-spring-initializr
    - dotjoshjohnson.xml
